### ISSUE TITLE
Feature request: Support for interface selection

### ISSUE THREAD

**Issue by chanduusc** [Gymmasssorla/anevicon#3]
Thanks for the great tool. It would be great if someone can add support to select network interface

**Comment by Gymmasssorla** [comment]
This's a good idea, I'll try to implement it soon.

**Comment by Gymmasssorla** [comment]
Done: https://github.com/Gymmasssorla/anevicon/commit/7a97cb3526e4b3608cac93125bd87c70e5400a36. Now fixing the errors and stabilizing a new `--select-if` option.

**Comment by chanduusc** [comment]
Thank you
